"""Modifications to Airports and Routes Models

Revision ID: 177a85985271
Revises: aa2c5718c701
Create Date: 2024-11-05 14:50:19.181862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177a85985271'
down_revision = 'aa2c5718c701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Airports', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['airport_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Airports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
