"""Adding Orders Model and Foreign Keys

Revision ID: 1f7c4a058830
Revises: 177a85985271
Create Date: 2024-11-05 15:24:56.837245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7c4a058830'
down_revision = '177a85985271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('order_status', sa.Enum('Completed', 'Scheduled', name='orderstatus'), nullable=False),
    sa.Column('order_route', sa.Integer(), nullable=False),
    sa.Column('order_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_route'], ['Routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Orders')
    # ### end Alembic commands ###
