"""Adding NewsArticle Model

Revision ID: 3afff464a09a
Revises: 98916152c5d4
Create Date: 2024-11-04 15:47:43.854294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3afff464a09a'
down_revision = '98916152c5d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('News',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_title', sa.String(length=30), nullable=False),
    sa.Column('article_content', sa.Text(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('article_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('News')
    # ### end Alembic commands ###
