"""Adding NewsArticle Model

Revision ID: 58aa684e07ca
Revises: 3afff464a09a
Create Date: 2024-11-04 16:34:46.635878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '58aa684e07ca'
down_revision = '3afff464a09a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('News', schema=None) as batch_op:
        batch_op.alter_column('updated_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('News', schema=None) as batch_op:
        batch_op.alter_column('updated_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###
