"""Adding Airports and Routes Models

Revision ID: aa2c5718c701
Revises: 58aa684e07ca
Create Date: 2024-11-05 11:28:10.940494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa2c5718c701'
down_revision = '58aa684e07ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Airports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airport_name', sa.String(length=50), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_airport', sa.Integer(), nullable=False),
    sa.Column('destination_airport', sa.Integer(), nullable=False),
    sa.Column('cost_per_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['destination_airport'], ['Airports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origin_airport'], ['Airports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Routes')
    op.drop_table('Airports')
    # ### end Alembic commands ###
